### ISSUE TITLE
Can you show the structure of the data set？ 

### ISSUE THREAD

**Issue by JianghaoWu** [neerakara/test-time-adaptable-neural-networks-for-domain-generalization#4]
Thank you for your excellent work. I want to run your code on my own data set, but I found  ConnectomeDB website is temporarily suspended. Can you provide the structure of the data set, or there are other ways to obtain the data? Thank you so much!

**Comment by neerakara** [comment]
Hi Jianghao,

Thanks for reaching out. Unfortunately, I do not know of another way to download the data. As far as the structure of the data is concerned, I believe this should be clear from the code in the data loader. If you have further specific questions, please feel free to ask - I will be very happy to clarify.

Best,
Neerav
